name: Build and Release

on:
  push:
    paths:
      - '**.ts'
      - 'CHANGELOG.md'
      - '.github/workflows/**'
env:
  artifact-name: 测试版

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          tsc
          webpack
          
          output=$(node packer.js --workflow)
          line="$(
            # 获取js输出，是否release
            if [[ $(echo $output | awk '{print $2}') == "true" ]]; then
              echo "true"
            else
              echo "false"
            fi
          )"
          echo "isrelease=$line" >> $GITHUB_ENV
        timeout-minutes: 1

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact-name }}
          path: ${{ github.workspace }}/build/
          compression-level: 0


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: env.isrelease == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/dist
          name: ${{ env.artifact-name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: ${{ github.workspace }}/dist/*
          body_path: ${{ github.workspace }}/CHANGELOG.md